### ISSUE TITLE
Methods and Execution styling - For reference

### ISSUE THREAD

**Issue by kirstengreen** [marcusrelacion/kirstengreen.com#16]
![Screen Shot 2019-10-12 at 5 52 01 PM](https://user-images.githubusercontent.com/10482373/66708073-02e46a80-ed19-11e9-9462-6369d7244116.png)

**Comment by marcusrelacion** [comment]
Fixed in https://github.com/marcusrelacion/kirstengreen.com/commit/0b4057f4082a78f29f266161a23e42fbf5b941d3
